#!/bin/bash

clear

barra="\033[0m\e[34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"

##SCRIPTS A INSTALAR

## Telegram: @asas_dev

INTALL_DTUNEL_PROXY () {
     bash <(wget -qO- https://asasdev.tk/dtunel-proxy/intdt.sh)
}
GERENCIAR_DTUNEL_PROXY () {
     clear
     dtunel_proxy
}
VOLTAR () {
    clear
    conexao
}

while true $x != "ok"
do
clear
echo -e "\033[0;34m═══════════════════•⊱✦⊰•══════════════════\033[0m"
echo -e "\E[41;1;37m    ✩         DTUNEL PROXY          ✩     \E[0m"
echo -e "\033[0;34m═══════════════════•⊱✦⊰•══════════════════\033[0m"
echo -e "\033[1;31m  [\033[1;36m01\033[1;31m] \033[1;37m• \033[1;37mINSTALAR  \033[1;31m>\033[1;33m>\033[1;32m> \033[1;37mDTUNEL PROXY
\033[1;31m  [\033[1;36m02\033[1;31m] \033[1;37m• \033[1;37mGERENCIAR \033[1;31m>\033[1;33m>\033[1;32m> \033[1;37mDTUNEL PROXY
\033[1;31m  [\033[1;36m03\033[1;31m] \033[1;37m• \033[1;37mMENU \033[1;31m>\033[1;33m>\033[1;32m>\033[0m
\033[1;31m  [\033[1;36m00\033[1;31m] \033[1;37m• \033[1;37mSAIR \033[1;31m>\033[1;33m>\033[1;32m>\033[0m"
echo -e "\033[0;34m═══════════════════•⊱✦⊰•══════════════════\033[0m"
echo ""
echo -ne "\033[1;32m O QUE DESEJA FAZER \033[1;33m?\033[1;31m?\033[1;37m : "; read x

case "$x" in 
   1 | 01)
   clear
   INTALL_DTUNEL_PROXY   
   exit;
   ;;
   2 | 02)
   clear
   GERENCIAR_DTUNEL_PROXY   
   exit;
   ;;
   3 | 03)
   clear
   VOLTAR
   exit;
   ;;
   0 | 00)
   echo -e "\033[1;31mSaindo...\033[0m"
   sleep 2
   clear
   exit;
   ;;
   *)
   echo -e "\n\033[1;31mOpcao invalida !\033[0m"
   sleep 2
esac
done
}
#fim

